### ISSUE TITLE
pg_dump incorrectly generate cleanup for external tables

### ISSUE THREAD

**Issue by eshkinkot** [arenadata/db#1025]
pg_dump incorrectly generate cleanup for external tables, for example:
```
pg_dump -s -c -t aaa.bbb
...
SET client_min_messages = warning;

DROP EXTERNAL TABLE aaa.bbb.SET default_tablespace = '';

SET default_with_oids = false;
...
```

There is a typo here: https://github.com/arenadata/gpdb/blob/59494d743fb12005b3a27f11615b10c4d0ef2ab3/src/bin/pg_dump/pg_dump.c#L13116

**Comment by Stolb27** [comment]
Opened a ticket in the our tracker: ADBDEV-6256

**Comment by Stolb27** [comment]
Fixed in https://github.com/arenadata/gpdb/commit/eaafa97a524e34f6533b5b5ee406fce5bf430d94
